name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Get latest tag
      id: get_tag
      run: |
        git fetch --tags
        echo "TAG=$(git describe --tags --abbrev=0 || echo v0.0.0)" >> $GITHUB_OUTPUT

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.wodoxo.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ steps.get_tag.outputs.TAG }}
      run: |
        docker build . --file backend.dockerfile --tag registry.wodoxo.com/everva/perp-ai-backend:$IMAGE_TAG
        docker push registry.wodoxo.com/everva/perp-ai-backend:$IMAGE_TAG
