name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Get latest tag
      id: get_tag
      run: |
        git fetch --tags
        echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Increment tag
      id: increment_tag
      run: |
        CURRENT_TAG=$(echo $TAG)
        MAJOR=$(echo $CURRENT_TAG | cut -d. -f1)
        MINOR=$(echo $CURRENT_TAG | cut -d. -f2)
        PATCH=$(echo $CURRENT_TAG | cut -d. -f3)
        NEXT_PATCH=$((PATCH + 1))
        INCREMENTED_TAG=$MAJOR.$MINOR.$NEXT_PATCH
        echo "INCREMENTED_TAG=$INCREMENTED_TAG" >> $GITHUB_ENV

    - name: Push tag to repository
      run: |
        git config --local user.email "atknatk@gmail.com"
        git config --local user.name "Atakan Atik"
        git tag $INCREMENTED_TAG
        git push origin $INCREMENTED_TAG

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.wodoxo.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ env.INCREMENTED_TAG }}
      run: |
        docker build . --file backend.dockerfile --tag registry.wodoxo.com/everva/perp-ai-backend:$IMAGE_TAG
        docker push registry.wodoxo.com/everva/perp-ai-backend:$IMAGE_TAG
